### ISSUE TITLE
能否新增获取宽带的上传速度和下载速度

### ISSUE THREAD

**Issue by mengsiyitiaojie** [mdddj/flutter_network_connection#1]
能否新增获取宽带的上传速度和下载速度

**Comment by mdddj** [comment]
> 可以加入宽带的上传速度和下载速度

有空再加

**Comment by mengsiyitiaojie** [comment]
谢谢  插件很好

**Comment by mengsiyitiaojie** [comment]
> > 可以加入宽带的上传速度和下载速度
> 
> 有空再加

请问大佬什么时候可以加上 急用

**Comment by mdddj** [comment]
> > > 可以加入宽带的上传速度和下载速度
> > 
> > 
> > 有空再加
> 
> 请问大佬什么时候可以加上 急用

我也不确定,最近太忙了

**Comment by mengsiyitiaojie** [comment]
希望可以加上
