### ISSUE TITLE
使用TraceRoute类型咋得不到mtu值呢

### ISSUE THREAD

**Issue by mengsiyitiaojie** [mdddj/flutter_network_connection#2]
使用TraceRoute类型咋得不到mtu值呢 可以获取mtu值吗

**Comment by mdddj** [comment]
> 使用TraceRoute类型咋得不到mtu值呢 可以获取mtu值吗

![image](https://user-images.githubusercontent.com/29020213/120954926-d0f00980-c782-11eb-9498-b1da8c2b6883.png)

试试这个
