### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel flutter_network_connection_eventkey)

### ISSUE THREAD

**Issue by GreatZheng2023** [mdddj/flutter_network_connection#3]
FlutterNetworkConnection.instance.start('http://baidu.com', sourceData: (String result) {
      _data = result;
      setState(() {});
    });

使用之后提示

MissingPluginException(No implementation found for method listen on channel flutter_network_connection_eventkey)

**Comment by mdddj** [comment]
不支持ios
